[[redirects]]
from = "/*"
to = "https://express-react-trello-api.onrender.com/"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
